/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MainRouteRouteImport } from './routes/_main/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as MainIndexRouteImport } from './routes/_main/index'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as MainBusinessIdRouteRouteImport } from './routes/_main/$businessId/route'
import { Route as MainBusinessIdIndexRouteImport } from './routes/_main/$businessId/index'
import { Route as MainBusinessIdProductsRouteImport } from './routes/_main/$businessId/products'
import { Route as MainBusinessIdOrdersRouteImport } from './routes/_main/$businessId/orders'
import { Route as MainBusinessIdInventoryRouteImport } from './routes/_main/$businessId/inventory'
import { Route as MainBusinessIdHomeRouteImport } from './routes/_main/$businessId/home'
import { Route as MainBusinessIdDraft_ordersRouteImport } from './routes/_main/$businessId/draft_orders'
import { Route as MainBusinessIdCustomersRouteImport } from './routes/_main/$businessId/customers'
import { Route as MainBusinessIdSplatRouteImport } from './routes/_main/$businessId/$'
import { Route as MainBusinessIdProductsIndexRouteImport } from './routes/_main/$businessId/products/index'
import { Route as MainBusinessIdOrdersIndexRouteImport } from './routes/_main/$businessId/orders/index'
import { Route as MainBusinessIdProductsNewRouteImport } from './routes/_main/$businessId/products/new'
import { Route as MainBusinessIdProductsProductIdRouteImport } from './routes/_main/$businessId/products/$productId'
import { Route as MainBusinessIdOrdersNewRouteImport } from './routes/_main/$businessId/orders/new'
import { Route as MainBusinessIdOrdersOrderIdRouteImport } from './routes/_main/$businessId/orders/$orderId'

const MainRouteRoute = MainRouteRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRouteRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const MainBusinessIdRouteRoute = MainBusinessIdRouteRouteImport.update({
  id: '/$businessId',
  path: '/$businessId',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainBusinessIdIndexRoute = MainBusinessIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainBusinessIdRouteRoute,
} as any)
const MainBusinessIdProductsRoute = MainBusinessIdProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => MainBusinessIdRouteRoute,
} as any)
const MainBusinessIdOrdersRoute = MainBusinessIdOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => MainBusinessIdRouteRoute,
} as any)
const MainBusinessIdInventoryRoute = MainBusinessIdInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => MainBusinessIdRouteRoute,
} as any)
const MainBusinessIdHomeRoute = MainBusinessIdHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => MainBusinessIdRouteRoute,
} as any)
const MainBusinessIdDraft_ordersRoute =
  MainBusinessIdDraft_ordersRouteImport.update({
    id: '/draft_orders',
    path: '/draft_orders',
    getParentRoute: () => MainBusinessIdRouteRoute,
  } as any)
const MainBusinessIdCustomersRoute = MainBusinessIdCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => MainBusinessIdRouteRoute,
} as any)
const MainBusinessIdSplatRoute = MainBusinessIdSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => MainBusinessIdRouteRoute,
} as any)
const MainBusinessIdProductsIndexRoute =
  MainBusinessIdProductsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => MainBusinessIdProductsRoute,
  } as any)
const MainBusinessIdOrdersIndexRoute =
  MainBusinessIdOrdersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => MainBusinessIdOrdersRoute,
  } as any)
const MainBusinessIdProductsNewRoute =
  MainBusinessIdProductsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => MainBusinessIdProductsRoute,
  } as any)
const MainBusinessIdProductsProductIdRoute =
  MainBusinessIdProductsProductIdRouteImport.update({
    id: '/$productId',
    path: '/$productId',
    getParentRoute: () => MainBusinessIdProductsRoute,
  } as any)
const MainBusinessIdOrdersNewRoute = MainBusinessIdOrdersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => MainBusinessIdOrdersRoute,
} as any)
const MainBusinessIdOrdersOrderIdRoute =
  MainBusinessIdOrdersOrderIdRouteImport.update({
    id: '/$orderId',
    path: '/$orderId',
    getParentRoute: () => MainBusinessIdOrdersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof MainIndexRoute
  '/$businessId': typeof MainBusinessIdRouteRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/$businessId/$': typeof MainBusinessIdSplatRoute
  '/$businessId/customers': typeof MainBusinessIdCustomersRoute
  '/$businessId/draft_orders': typeof MainBusinessIdDraft_ordersRoute
  '/$businessId/home': typeof MainBusinessIdHomeRoute
  '/$businessId/inventory': typeof MainBusinessIdInventoryRoute
  '/$businessId/orders': typeof MainBusinessIdOrdersRouteWithChildren
  '/$businessId/products': typeof MainBusinessIdProductsRouteWithChildren
  '/$businessId/': typeof MainBusinessIdIndexRoute
  '/$businessId/orders/$orderId': typeof MainBusinessIdOrdersOrderIdRoute
  '/$businessId/orders/new': typeof MainBusinessIdOrdersNewRoute
  '/$businessId/products/$productId': typeof MainBusinessIdProductsProductIdRoute
  '/$businessId/products/new': typeof MainBusinessIdProductsNewRoute
  '/$businessId/orders/': typeof MainBusinessIdOrdersIndexRoute
  '/$businessId/products/': typeof MainBusinessIdProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof MainIndexRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/$businessId/$': typeof MainBusinessIdSplatRoute
  '/$businessId/customers': typeof MainBusinessIdCustomersRoute
  '/$businessId/draft_orders': typeof MainBusinessIdDraft_ordersRoute
  '/$businessId/home': typeof MainBusinessIdHomeRoute
  '/$businessId/inventory': typeof MainBusinessIdInventoryRoute
  '/$businessId': typeof MainBusinessIdIndexRoute
  '/$businessId/orders/$orderId': typeof MainBusinessIdOrdersOrderIdRoute
  '/$businessId/orders/new': typeof MainBusinessIdOrdersNewRoute
  '/$businessId/products/$productId': typeof MainBusinessIdProductsProductIdRoute
  '/$businessId/products/new': typeof MainBusinessIdProductsNewRoute
  '/$businessId/orders': typeof MainBusinessIdOrdersIndexRoute
  '/$businessId/products': typeof MainBusinessIdProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_main': typeof MainRouteRouteWithChildren
  '/_main/$businessId': typeof MainBusinessIdRouteRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_main/': typeof MainIndexRoute
  '/_main/$businessId/$': typeof MainBusinessIdSplatRoute
  '/_main/$businessId/customers': typeof MainBusinessIdCustomersRoute
  '/_main/$businessId/draft_orders': typeof MainBusinessIdDraft_ordersRoute
  '/_main/$businessId/home': typeof MainBusinessIdHomeRoute
  '/_main/$businessId/inventory': typeof MainBusinessIdInventoryRoute
  '/_main/$businessId/orders': typeof MainBusinessIdOrdersRouteWithChildren
  '/_main/$businessId/products': typeof MainBusinessIdProductsRouteWithChildren
  '/_main/$businessId/': typeof MainBusinessIdIndexRoute
  '/_main/$businessId/orders/$orderId': typeof MainBusinessIdOrdersOrderIdRoute
  '/_main/$businessId/orders/new': typeof MainBusinessIdOrdersNewRoute
  '/_main/$businessId/products/$productId': typeof MainBusinessIdProductsProductIdRoute
  '/_main/$businessId/products/new': typeof MainBusinessIdProductsNewRoute
  '/_main/$businessId/orders/': typeof MainBusinessIdOrdersIndexRoute
  '/_main/$businessId/products/': typeof MainBusinessIdProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$businessId'
    | '/login'
    | '/register'
    | '/$businessId/$'
    | '/$businessId/customers'
    | '/$businessId/draft_orders'
    | '/$businessId/home'
    | '/$businessId/inventory'
    | '/$businessId/orders'
    | '/$businessId/products'
    | '/$businessId/'
    | '/$businessId/orders/$orderId'
    | '/$businessId/orders/new'
    | '/$businessId/products/$productId'
    | '/$businessId/products/new'
    | '/$businessId/orders/'
    | '/$businessId/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/$businessId/$'
    | '/$businessId/customers'
    | '/$businessId/draft_orders'
    | '/$businessId/home'
    | '/$businessId/inventory'
    | '/$businessId'
    | '/$businessId/orders/$orderId'
    | '/$businessId/orders/new'
    | '/$businessId/products/$productId'
    | '/$businessId/products/new'
    | '/$businessId/orders'
    | '/$businessId/products'
  id:
    | '__root__'
    | '/_auth'
    | '/_main'
    | '/_main/$businessId'
    | '/_auth/login'
    | '/_auth/register'
    | '/_main/'
    | '/_main/$businessId/$'
    | '/_main/$businessId/customers'
    | '/_main/$businessId/draft_orders'
    | '/_main/$businessId/home'
    | '/_main/$businessId/inventory'
    | '/_main/$businessId/orders'
    | '/_main/$businessId/products'
    | '/_main/$businessId/'
    | '/_main/$businessId/orders/$orderId'
    | '/_main/$businessId/orders/new'
    | '/_main/$businessId/products/$productId'
    | '/_main/$businessId/products/new'
    | '/_main/$businessId/orders/'
    | '/_main/$businessId/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  MainRouteRoute: typeof MainRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_main/$businessId': {
      id: '/_main/$businessId'
      path: '/$businessId'
      fullPath: '/$businessId'
      preLoaderRoute: typeof MainBusinessIdRouteRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/$businessId/': {
      id: '/_main/$businessId/'
      path: '/'
      fullPath: '/$businessId/'
      preLoaderRoute: typeof MainBusinessIdIndexRouteImport
      parentRoute: typeof MainBusinessIdRouteRoute
    }
    '/_main/$businessId/products': {
      id: '/_main/$businessId/products'
      path: '/products'
      fullPath: '/$businessId/products'
      preLoaderRoute: typeof MainBusinessIdProductsRouteImport
      parentRoute: typeof MainBusinessIdRouteRoute
    }
    '/_main/$businessId/orders': {
      id: '/_main/$businessId/orders'
      path: '/orders'
      fullPath: '/$businessId/orders'
      preLoaderRoute: typeof MainBusinessIdOrdersRouteImport
      parentRoute: typeof MainBusinessIdRouteRoute
    }
    '/_main/$businessId/inventory': {
      id: '/_main/$businessId/inventory'
      path: '/inventory'
      fullPath: '/$businessId/inventory'
      preLoaderRoute: typeof MainBusinessIdInventoryRouteImport
      parentRoute: typeof MainBusinessIdRouteRoute
    }
    '/_main/$businessId/home': {
      id: '/_main/$businessId/home'
      path: '/home'
      fullPath: '/$businessId/home'
      preLoaderRoute: typeof MainBusinessIdHomeRouteImport
      parentRoute: typeof MainBusinessIdRouteRoute
    }
    '/_main/$businessId/draft_orders': {
      id: '/_main/$businessId/draft_orders'
      path: '/draft_orders'
      fullPath: '/$businessId/draft_orders'
      preLoaderRoute: typeof MainBusinessIdDraft_ordersRouteImport
      parentRoute: typeof MainBusinessIdRouteRoute
    }
    '/_main/$businessId/customers': {
      id: '/_main/$businessId/customers'
      path: '/customers'
      fullPath: '/$businessId/customers'
      preLoaderRoute: typeof MainBusinessIdCustomersRouteImport
      parentRoute: typeof MainBusinessIdRouteRoute
    }
    '/_main/$businessId/$': {
      id: '/_main/$businessId/$'
      path: '/$'
      fullPath: '/$businessId/$'
      preLoaderRoute: typeof MainBusinessIdSplatRouteImport
      parentRoute: typeof MainBusinessIdRouteRoute
    }
    '/_main/$businessId/products/': {
      id: '/_main/$businessId/products/'
      path: '/'
      fullPath: '/$businessId/products/'
      preLoaderRoute: typeof MainBusinessIdProductsIndexRouteImport
      parentRoute: typeof MainBusinessIdProductsRoute
    }
    '/_main/$businessId/orders/': {
      id: '/_main/$businessId/orders/'
      path: '/'
      fullPath: '/$businessId/orders/'
      preLoaderRoute: typeof MainBusinessIdOrdersIndexRouteImport
      parentRoute: typeof MainBusinessIdOrdersRoute
    }
    '/_main/$businessId/products/new': {
      id: '/_main/$businessId/products/new'
      path: '/new'
      fullPath: '/$businessId/products/new'
      preLoaderRoute: typeof MainBusinessIdProductsNewRouteImport
      parentRoute: typeof MainBusinessIdProductsRoute
    }
    '/_main/$businessId/products/$productId': {
      id: '/_main/$businessId/products/$productId'
      path: '/$productId'
      fullPath: '/$businessId/products/$productId'
      preLoaderRoute: typeof MainBusinessIdProductsProductIdRouteImport
      parentRoute: typeof MainBusinessIdProductsRoute
    }
    '/_main/$businessId/orders/new': {
      id: '/_main/$businessId/orders/new'
      path: '/new'
      fullPath: '/$businessId/orders/new'
      preLoaderRoute: typeof MainBusinessIdOrdersNewRouteImport
      parentRoute: typeof MainBusinessIdOrdersRoute
    }
    '/_main/$businessId/orders/$orderId': {
      id: '/_main/$businessId/orders/$orderId'
      path: '/$orderId'
      fullPath: '/$businessId/orders/$orderId'
      preLoaderRoute: typeof MainBusinessIdOrdersOrderIdRouteImport
      parentRoute: typeof MainBusinessIdOrdersRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface MainBusinessIdOrdersRouteChildren {
  MainBusinessIdOrdersOrderIdRoute: typeof MainBusinessIdOrdersOrderIdRoute
  MainBusinessIdOrdersNewRoute: typeof MainBusinessIdOrdersNewRoute
  MainBusinessIdOrdersIndexRoute: typeof MainBusinessIdOrdersIndexRoute
}

const MainBusinessIdOrdersRouteChildren: MainBusinessIdOrdersRouteChildren = {
  MainBusinessIdOrdersOrderIdRoute: MainBusinessIdOrdersOrderIdRoute,
  MainBusinessIdOrdersNewRoute: MainBusinessIdOrdersNewRoute,
  MainBusinessIdOrdersIndexRoute: MainBusinessIdOrdersIndexRoute,
}

const MainBusinessIdOrdersRouteWithChildren =
  MainBusinessIdOrdersRoute._addFileChildren(MainBusinessIdOrdersRouteChildren)

interface MainBusinessIdProductsRouteChildren {
  MainBusinessIdProductsProductIdRoute: typeof MainBusinessIdProductsProductIdRoute
  MainBusinessIdProductsNewRoute: typeof MainBusinessIdProductsNewRoute
  MainBusinessIdProductsIndexRoute: typeof MainBusinessIdProductsIndexRoute
}

const MainBusinessIdProductsRouteChildren: MainBusinessIdProductsRouteChildren =
  {
    MainBusinessIdProductsProductIdRoute: MainBusinessIdProductsProductIdRoute,
    MainBusinessIdProductsNewRoute: MainBusinessIdProductsNewRoute,
    MainBusinessIdProductsIndexRoute: MainBusinessIdProductsIndexRoute,
  }

const MainBusinessIdProductsRouteWithChildren =
  MainBusinessIdProductsRoute._addFileChildren(
    MainBusinessIdProductsRouteChildren,
  )

interface MainBusinessIdRouteRouteChildren {
  MainBusinessIdSplatRoute: typeof MainBusinessIdSplatRoute
  MainBusinessIdCustomersRoute: typeof MainBusinessIdCustomersRoute
  MainBusinessIdDraft_ordersRoute: typeof MainBusinessIdDraft_ordersRoute
  MainBusinessIdHomeRoute: typeof MainBusinessIdHomeRoute
  MainBusinessIdInventoryRoute: typeof MainBusinessIdInventoryRoute
  MainBusinessIdOrdersRoute: typeof MainBusinessIdOrdersRouteWithChildren
  MainBusinessIdProductsRoute: typeof MainBusinessIdProductsRouteWithChildren
  MainBusinessIdIndexRoute: typeof MainBusinessIdIndexRoute
}

const MainBusinessIdRouteRouteChildren: MainBusinessIdRouteRouteChildren = {
  MainBusinessIdSplatRoute: MainBusinessIdSplatRoute,
  MainBusinessIdCustomersRoute: MainBusinessIdCustomersRoute,
  MainBusinessIdDraft_ordersRoute: MainBusinessIdDraft_ordersRoute,
  MainBusinessIdHomeRoute: MainBusinessIdHomeRoute,
  MainBusinessIdInventoryRoute: MainBusinessIdInventoryRoute,
  MainBusinessIdOrdersRoute: MainBusinessIdOrdersRouteWithChildren,
  MainBusinessIdProductsRoute: MainBusinessIdProductsRouteWithChildren,
  MainBusinessIdIndexRoute: MainBusinessIdIndexRoute,
}

const MainBusinessIdRouteRouteWithChildren =
  MainBusinessIdRouteRoute._addFileChildren(MainBusinessIdRouteRouteChildren)

interface MainRouteRouteChildren {
  MainBusinessIdRouteRoute: typeof MainBusinessIdRouteRouteWithChildren
  MainIndexRoute: typeof MainIndexRoute
}

const MainRouteRouteChildren: MainRouteRouteChildren = {
  MainBusinessIdRouteRoute: MainBusinessIdRouteRouteWithChildren,
  MainIndexRoute: MainIndexRoute,
}

const MainRouteRouteWithChildren = MainRouteRoute._addFileChildren(
  MainRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  MainRouteRoute: MainRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
